#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jpam
Version  : 1.1
Release  : 2
URL      : https://repo1.maven.org/maven2/net/sf/jpam/jpam/1.1/jpam-1.1.jar
Source0  : https://repo1.maven.org/maven2/net/sf/jpam/jpam/1.1/jpam-1.1.jar
Source1  : https://repo1.maven.org/maven2/net/sf/jpam/jpam/1.1/jpam-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jpam-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jpam package.
Group: Data

%description data
data components for the mvn-jpam package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/jpam/jpam/1.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/net/sf/jpam/jpam/1.1/jpam-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/jpam/jpam/1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sf/jpam/jpam/1.1/jpam-1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sf/jpam/jpam/1.1/jpam-1.1.jar
/usr/share/java/.m2/repository/net/sf/jpam/jpam/1.1/jpam-1.1.pom
